
module.exports = {
    PEOPLE: "PEOPLE",
    PERMISSIONS: "PERMISSIONS",
    ENTRANCE_LOGS: "ENTRANCE_LOGS",
    ENTRANCE_LOG_IMAGES: "ENTRANCE_LOG_IMAGES",
    SENSOR_LOGS: "SENSOR_LOGS",
    ACTUATOR_LOGS: "ACTUATOR_LOGS",
    EVENTS: "EVENTS"
};
